id: P006886
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017048
  title: གྲུབ་པའི་དབང་ཕྱུག་སྒྲུབ་བརྒྱུད་དཔའ་བོ་སྟག་ཤམ་ཅན་སྐུ་རབས་རིམ་བྱོན་གྱི་རྣམ་པར་ཐར་པ་མདོ་ཙམ་བརྗོད་པ་རྫོགས་ལྡན་གསར་པའི་དགའ་སྟོན
  author: ''
  volumes: {}
